server:
  port: 8383

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - AuthenticationFilter

        - id: SALARY-SERVICE
          uri: lb://SALARY-SERVICE
          predicates:
            - Path=/api/v1/salary/**,/api/v1/leaves/**
          filters:
            - AuthenticationFilter

        - id: AUTH-SERVER
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthenticationFilter

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
