server:
  port: 8585

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authDb
    username: postgres
    password: Raja@nagar08
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  mail:
#    host: sandbox.smtp.mailtrap.io
#    port: 587
#    username: 9c0edc607f5541
#    password: 3401eec685664c
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true

  application:
    name: AUTH-SERVER

  config:
    import: configserver:http://localhost:8484

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
      #eureka:
      #  instance:
      #    prefer-ip-address: true
      #  client:
      #    fetch-registry: true
      #    register-with-eureka: true
      #    service-url:
      #      defaultZone: http://localhost:8761/eureka



