server:
  port: 8484

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rajdeep-nagar08/payroll-microservice-config
          clone-on-start: true

